# Generated by Django 2.0.3 on 2024-03-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('cbuys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('comm_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('combuys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('his_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=225)),
                ('hbuys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='newschanel',
            fields=[
                ('nch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('clogins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('buys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rated', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('rbuys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('ulogins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('video', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='husers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='comusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.user'),
        ),
        migrations.AddField(
            model_name='buy',
            name='nchs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.newschanel'),
        ),
        migrations.AddField(
            model_name='buy',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsrateapp.video'),
        ),
    ]
